<?php
  /**
   * Engage Commerce
   *
   * NOTICE OF LICENSE
   *
   * This source file is subject to the Open Software License (OSL 3.0)
   * that is bundled with this package in the file LICENSE.txt.
   * It is also available through the world-wide-web at this URL:
   * http://opensource.org/licenses/osl-3.0.php
   * If you did not receive a copy of the license and are unable to
   * obtain it through the world-wide-web, please send an email
   * to license@magentocommerce.com so we can send you a copy immediately.
   *
   * @category    EngageCommerce
   * @package     EngageCommerce_LinkedIn
   * @copyright   Copyright (c) 2016 Engage Commerce (http://engagecommerce.io)
   * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
   */
  $pixelHelper = Mage::helper("engagecommerce_linkedin");
  $pixelId = $pixelHelper->getPixelId();
  $pixelArr = array_filter(array_map('trim', explode(',', $pixelId)), 'strlen');
?>

<?php if (count($pixelArr) === 1): ?>
  <!-- Engage Commerce: Linkedin Insight Tag Code -->
  <script type="text/javascript">
       _biz0_data_partner_id = '<?php echo $pixelArr[0] ?>';
  </script>
  <script type="text/javascript">
      (function() {
          var s = document.getElementsByTagName("script")[0];
          var b = document.createElement("script");
          b.type = "text/javascript";
          b.async = true;
          b.src = (window.location.protocol === "https:" ? "https://sjs" : "http://js") + ".bizographics.com/insight.min.js";
          s.parentNode.insertBefore(b, s);
      })();
  </script>
  <noscript>
      <img height="1" width="1" alt="" style="display:none;" src="//www.bizographics.com/collect/?pid=<?php echo $pixelArr[0] ?>&fmt=gif" />
  </noscript>
<?php else: ?>
  <!-- Engage Commerce: Linkedin Insight Tag Code -->
  <?php foreach($pixelArr as $id): ?>
    <img height="1" width="1" alt="" style="display:none;" src="//www.bizographics.com/collect/?pid=<?php echo $id ?>&fmt=gif" />
  <? endforeach; ?>
<?php endif; ?>
